AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GitHub OAuth Lambda

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 20

Resources:
  GitHubOAuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.handler
      Environment:
        Variables:
          GITHUB_CLIENT_ID: "Ov23li1hTQlkn4BALtEq"
          GITHUB_CLIENT_SECRET: "10f141255a59e3ce8ef5be3f2a55186f6c8cdc88"
          REDIRECT_URI: "https://n0bmcwctpk.execute-api.eu-north-1.amazonaws.com/Prod/oauth/callback"
      Events:
        OAuthCallback:
          Type: Api
          Properties:
            Path: /oauth/callback
            Method: get

Outputs:
  GitHubOAuthApiUrl:
    Description: "API Gateway endpoint for GitHub OAuth callback"
    Value: !Sub "https://${GitHubOAuthLambda}.execute-api.${AWS::Region}.amazonaws.com/Prod/oauth/callback"
